# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
     npm install
  displayName: 'npm install and test'

#SCA using whitesource start######
- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'pghodki/ScanGHfromAzDO'
# SCA using whitesource end######

# instead of public repo we can use vetted private repo/artifactory location
- script: |
      wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
        chmod +x codeql-runner-linux
  displayName: 'Get latest CodeQL package. Install on Agent.'

- script: |
    ./codeql-runner-linux init \
    --repository pghodki/ScanGHfromAzDO \
    --github-url https://github.com \
    --github-auth $(GITHUB_PAT) \
    --config-file .github/codeql/codeql-config.yml 
  displayName: 'Initialize CodeQL Executable and create a CodeQL database'
  
- script: |
    ./codeql-runner-linux analyze \
    --repository pghodki/ScanGHfromAzDO \
    --github-url https://github.com \
    --github-auth $(GITHUB_PAT) \
    --commit $(Build.SourceVersion) \
    --ref $(Build.SourceBranch)
  displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'

- script: |
      wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
      mkdir zap
      tar -xvf ZAP_2.11.1_Linux.tar.gz
      cd ZAP_2.11.1
      ./zap.sh -cmd -quickurl https://example.com -quickprogress -quickout /home/vsts/work/1/a/zap_report.html
  displayName: "Integrate DAST using OWASP ZAP"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: zap_report.html

